(define hello "Heller")
(define g-spr -1)

(define (tor)
  (display "tor")
  )

(define (init)
  (display "Hello, World!")
  ;; (init-window 800 600 "Rebel Engine")
  (test-func)
  (display (test-func-2))
  (display "============== Getting sprite")
  (newline)
  (display (l-sprite-get-vao (create-sprite "assets/textures" "tile.png")))
  (set! g-spr (create-sprite "assets/textures" "tile.png"))

  (display "Done")
  (set! hello "HOLA")
  display (l-sprite-get-vao sprite))
  #t)

(define (draw)
  ;; (let ((spr-vao (l-sprite-get-vao g-spr)))
  ;;   (display ">>>>")
  ;;   (display spr-vao)
  ;;   (draw-sprite g-spr 50.0 50.0)
  ;;   )
  )
